### ISSUE TITLE
MacOS Mojave?

### ISSUE THREAD

**Issue by garzdin** [jakeh12/atmel-ice-mac-driver#1]
Does this work on Mojave? I don't get the device listed under /dev. Is that normal?

**Comment by jakeh12** [comment]
Hi @garzdin ,

I believe that the device should pop up in the /dev no matter what. I no longer have a test setup to test it with Mojave, but if I recall correctly, MacOS was correctly recognizing the device but the avrdude was written using libsusb and the default MacOS driver was causing the device not to be accessible through the libusb library. So to answer you question, it should be visible if you plug it in, even without the workaround. Do you get anything if you do `lsusb` command? Do you have a Linux machine to try it on besides your Mac?
